// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAGTaMKEvkeRRPswsxti0DQzi1CyAdkPk',
    appId: '1:426700103849:web:0b08d9670392773e3f49b8',
    messagingSenderId: '426700103849',
    projectId: 'mody-101',
    authDomain: 'mody-101.firebaseapp.com',
    storageBucket: 'mody-101.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAewW-slnIDPezcGzmrFaCGZxdrqQ5xynM',
    appId: '1:426700103849:android:0d74c13d623aa99b3f49b8',
    messagingSenderId: '426700103849',
    projectId: 'mody-101',
    storageBucket: 'mody-101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6KBoJf9QrNrpwBCw5OszmQJYLrfVXZv0',
    appId: '1:426700103849:ios:be67d05fa2734a8c3f49b8',
    messagingSenderId: '426700103849',
    projectId: 'mody-101',
    storageBucket: 'mody-101.firebasestorage.app',
    iosBundleId: 'com.example.modyAlumniConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6KBoJf9QrNrpwBCw5OszmQJYLrfVXZv0',
    appId: '1:426700103849:ios:be67d05fa2734a8c3f49b8',
    messagingSenderId: '426700103849',
    projectId: 'mody-101',
    storageBucket: 'mody-101.firebasestorage.app',
    iosBundleId: 'com.example.modyAlumniConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAGTaMKEvkeRRPswsxti0DQzi1CyAdkPk',
    appId: '1:426700103849:web:abf92f5855f8ecb83f49b8',
    messagingSenderId: '426700103849',
    projectId: 'mody-101',
    authDomain: 'mody-101.firebaseapp.com',
    storageBucket: 'mody-101.firebasestorage.app',
  );

}